[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hncu-sdk"
version = "0.1.0"
authors = [
  { name = "Yellowtown" },
]
description = "Python SDK for Hunan City University (湖南城市学院) Educational Administration & Campus Services"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
    "pycryptodome>=3.15.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com"
